language: php

cache:
    directories:
        - vendor

matrix:
  include:
    - php: 7.1
      env:
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.3

before_script:
    - phpenv config-rm xdebug.ini
    - COMPOSER_MEMORY_LIMIT=-1 travis_wait 20 composer update $COMPOSER_FLAGS
    - composer validate

script:
    - vendor/bin/phpspec run -f pretty
