language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
        - bin
        - vendor

matrix:
  include:
    - php: 7.1
      env:
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.1

before_script:
    - phpenv config-rm xdebug.ini
    - travis_wait 40 composer update $COMPOSER_FLAGS
    - composer validate

script:
    - bin/phpspec run -f pretty
